# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting macos)

source $ZSH/oh-my-zsh.sh

# Configs locais (não versionadas)
[ -f "$HOME/.zshrc.local" ] && source "$HOME/.zshrc.local"
